# -*- coding: utf-8 -*-
"""sushanth mini project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skf0KPfRL6pJXxbBHHwEzBIEW_klJF53
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Algorithms
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
import xgboost as xgb
import lightgbm as lgb

import warnings
warnings.filterwarnings('ignore')

print("Libraries Imported Successfully!")

"""# ***importing data***"""

df = pd.read_csv('crop_production.csv')
print(f"Data Loaded. Shape: {df.shape}")
print(df.head())

"""# **knowing about the data**"""

total_records = df.shape[0]
print("Total Records:", total_records)

print("Number of Unique Crops:", df['Crop'].nunique())
print(df['Crop'].unique())

print("Number of Unique Seasons:", df['Season'].nunique())
print(df['Season'].unique())

print("Number of States:", df['State'].nunique())

print(sorted(df['Year'].unique()))

print(df.isnull().sum())

print(df.describe())

print(df.info())

print(df.corr(numeric_only=True))

import matplotlib.pyplot as plt
df['Yield'].hist(bins=50)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv('crop_production.csv')

print("===== BASIC INFO =====")
print("Shape of dataset:", df.shape)
print("\nColumn Names:\n", df.columns)

print("\n===== DATA TYPES & NON-NULL COUNT =====")
print(df.info())

print("\n===== FIRST 5 ROWS =====")
print(df.head())


print("\n===== UNIQUE VALUES =====")

print("Number of Unique States:", df['State'].nunique())
print("Number of Unique Districts:", df['District'].nunique())
print("Number of Unique Crops:", df['Crop'].nunique())
print("Number of Unique Seasons:", df['Season'].nunique())
print("Number of Unique Years:", df['Year'].nunique())

print("\nUnique Seasons:", df['Season'].unique())
print("\nUnique Crops:", df['Crop'].unique())

print("\n===== MISSING VALUES =====")
print(df.isnull().sum())

print("\n===== STATISTICAL SUMMARY =====")
print(df.describe())

print("\n===== YIELD ANALYSIS =====")
print("Min Yield:", df['Yield'].min())
print("Max Yield:", df['Yield'].max())
print("Mean Yield:", df['Yield'].mean())
print("Median Yield:", df['Yield'].median())

print("\n===== CORRELATION MATRIX =====")
print(df.corr(numeric_only=True))

plt.figure()
df['Yield'].hist(bins=50)
plt.title("Yield Distribution")
plt.xlabel("Yield")
plt.ylabel("Frequency")
plt.show()

plt.figure()
df['Area'].hist(bins=50)
plt.title("Area Distribution")
plt.xlabel("Area")
plt.ylabel("Frequency")
plt.show()

plt.figure()
df['Production'].hist(bins=50)
plt.title("Production Distribution")
plt.xlabel("Production")
plt.ylabel("Frequency")
plt.show()

print("\n===== DUPLICATE ROWS =====")
print("Number of duplicate rows:", df.duplicated().sum())

print("\n===== YEAR COLUMN SAMPLE =====")
print(df['Year'].head())

# If year is like 2001-02, extract first year
df['Start_Year'] = df['Year'].str[:4].astype(int)

print("\nExtracted Start Year Sample:")
print(df[['Year','Start_Year']].head())





"""# **checking the data **"""

df_clean = df.copy()

# Drop unit columns (useless)
df_clean = df_clean.drop(['Area Units', 'Production Units'], axis=1)

# Drop rows where target is missing
df_clean = df_clean.dropna(subset=['Yield'])

# Drop rows where important categorical values missing
df_clean = df_clean.dropna(subset=['Crop', 'Season'])

print("Shape after cleaning:", df_clean.shape)

Q1 = df_clean['Yield'].quantile(0.25)
Q3 = df_clean['Yield'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df_clean = df_clean[(df_clean['Yield'] >= lower_bound) &
                    (df_clean['Yield'] <= upper_bound)]

print("Shape after removing outliers:", df_clean.shape)

df_clean = df_clean.drop(['Production', 'Area'], axis=1)

df_clean['Start_Year'] = df_clean['Year'].str[:4].astype(int)
df_clean = df_clean.drop('Year', axis=1)

print(df_clean.head())

"""# **random forest and linear regression**"""

from sklearn.preprocessing import LabelEncoder

df_model = df_clean.copy()

# Initialize encoder
le = LabelEncoder()

# Encode categorical columns
categorical_cols = ['State', 'District', 'Crop', 'Season']

for col in categorical_cols:
    df_model[col] = le.fit_transform(df_model[col])

print(df_model.head())

X = df_model.drop('Yield', axis=1)
y = df_model['Yield']

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training size:", X_train.shape)
print("Testing size:", X_test.shape)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("===== Linear Regression Results =====")
print("MAE:", mean_absolute_error(y_test, y_pred_lr))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lr)))
print("R2 Score:", r2_score(y_test, y_pred_lr))

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("\n===== Random Forest Results =====")
print("MAE:", mean_absolute_error(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))
print("R2 Score:", r2_score(y_test, y_pred_rf))

import pandas as pd

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
}).sort_values(by='Importance', ascending=False)

print("\n===== Feature Importance =====")
print(importance)

"""tune random forest"""

#this is will take 45 min - 1 hour o running the down one
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5]
}

rf_base = RandomForestRegressor(random_state=42)

grid_search = GridSearchCV(
    rf_base,
    param_grid,
    cv=3,
    scoring='r2',
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best CV Score:", grid_search.best_score_)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

configs = [
    {"n_estimators": 100, "max_depth": None},
    {"n_estimators": 200, "max_depth": None},
    {"n_estimators": 200, "max_depth": 20},
    {"n_estimators": 300, "max_depth": 20}
]

results = []

for config in configs:
    print(f"Training with {config}")

    rf = RandomForestRegressor(
        n_estimators=config["n_estimators"],
        max_depth=config["max_depth"],
        random_state=42,
        n_jobs=-1
    )

    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)
    r2 = r2_score(y_test, y_pred)

    print("R2:", r2)
    results.append((config, r2))

print("\nFinal Results:")
for res in results:
    print(res)

"""# **Random Forest “Epoch Simulation”**"""

import numpy as np
from sklearn.metrics import r2_score

tree_list = [10, 50, 100, 200]
rf_scores = []

for trees in tree_list:
    rf_temp = RandomForestRegressor(
        n_estimators=trees,
        random_state=42,
        n_jobs=-1
    )
    rf_temp.fit(X_train, y_train)
    y_pred = rf_temp.predict(X_test)
    score = r2_score(y_test, y_pred)
    rf_scores.append(score)
    print(f"Trees: {trees}, R2: {score}")

"""# **xg boost**"""



from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error

xgb = XGBRegressor(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=6,
    random_state=42,
    objective='reg:squarederror'
)

eval_set = [(X_train, y_train), (X_test, y_test)]

xgb.fit(
    X_train, y_train,
    eval_set=eval_set,
    verbose=True
)
from sklearn.metrics import r2_score

y_pred_xgb = xgb.predict(X_test)
xgb_r2 = r2_score(y_test, y_pred_xgb)

print("XGBoost R2:", xgb_r2)

"""# **graph**"""

import matplotlib.pyplot as plt

# Final RF score (use best from earlier)
final_rf_score = rf_scores[-1]

models = ['Linear Regression', 'Random Forest', 'XGBoost']
scores = [0.0315, final_rf_score, xgb_r2]

plt.figure()
plt.bar(models, scores)
plt.title("Model Comparison (R2 Score)")
plt.ylabel("R2 Score")
plt.show()

"""# ***save models***"""


import joblib

# Save Random Forest
joblib.dump(rf, 'random_forest_model.pkl')

print("Random Forest model saved successfully!")

joblib.dump(xgb, 'xgboost_model.pkl')

print("XGBoost model saved successfully!")

from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    df_model[col] = le.fit_transform(df_model[col])
    encoders[col] = le
joblib.dump(encoders, 'label_encoders.pkl')

print("Encoders saved successfully!")

joblib.dump(encoders, 'label_encoders.pkl')

print("Encoders saved successfully!")

from google.colab import files
files.download('random_forest_model.pkl')
files.download('xgboost_model.pkl')
files.download('label_encoders.pkl')

from google.colab import drive
drive.mount('/content/drive')

import joblib

joblib.dump(rf, '/content/drive/MyDrive/sushnaht_project/random_forest_model.pkl')
joblib.dump(xgb, '/content/drive/MyDrive/sushnaht_project/xgboost_model.pkl')
joblib.dump(encoders, '/content/drive/MyDrive/sushnaht_project/label_encoders.pkl')

print("Models saved to Google Drive successfully!")

"""# **model predection**

"""

# Pick one random sample from test set
sample_index = 10

sample_features = X_test.iloc[sample_index:sample_index+1]
actual_value = y_test.iloc[sample_index]

prediction = rf.predict(sample_features)

print("Actual Yield:", actual_value)
print("Predicted Yield:", prediction[0])

import matplotlib.pyplot as plt

y_pred = rf.predict(X_test)

plt.figure()
plt.scatter(y_test[:1000], y_pred[:1000])  # plotting 1000 points for clarity
plt.xlabel("Actual Yield")
plt.ylabel("Predicted Yield")
plt.title("Actual vs Predicted Yield (Random Forest)")
plt.show()

import joblib

rf = joblib.load('random_forest_model.pkl')
encoders = joblib.load('label_encoders.pkl')

categorical_cols = ['State', 'District', 'Crop', 'Season']

from sklearn.preprocessing import LabelEncoder

df_model = df_clean.copy()

categorical_cols = ['State', 'District', 'Crop', 'Season']

encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    df_model[col] = le.fit_transform(df_model[col].astype(str))
    encoders[col] = le

print("Encoding done correctly.")

print(encoders['State'].classes_[:20])

from sklearn.model_selection import train_test_split

X = df_model.drop('Yield', axis=1)
y = df_model['Yield']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=20,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

# Example new input
new_data = {
    'State': 'Karnataka',
    'District': 'BENGALURU',
    'Crop': 'Rice',
    'Season': 'Kharif',
    'Start_Year': 2020
}

# Convert to DataFrame
new_df = pd.DataFrame([new_data])

# Encode using saved encoders
for col in categorical_cols:
    new_df[col] = encoders[col].transform(new_df[col])

# Predict
prediction = rf.predict(new_df)

print("Predicted Yield:", prediction[0])

"""# **final one last and finalllll**"""

from google.colab import drive
drive.mount('/content/drive')

"""import libraries

"""

import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from xgboost import XGBRegressor

"""load dataset

"""

df = pd.read_csv('crop_production.csv')

print("Original Shape:", df.shape)

"""cleaning"""

# Drop unnecessary columns
df = df.drop(['Area Units', 'Production Units'], axis=1)

# Drop missing important values
df = df.dropna(subset=['Yield', 'Crop', 'Season'])

# Extract start year
df['Start_Year'] = df['Year'].str[:4].astype(int)
df = df.drop('Year', axis=1)

print("Shape after basic cleaning:", df.shape)

"""remove outliers"""

Q1 = df['Yield'].quantile(0.25)
Q3 = df['Yield'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df['Yield'] >= lower) & (df['Yield'] <= upper)]

print("Shape after outlier removal:", df.shape)

"""drop leak coloums

"""

df = df.drop(['Production', 'Area'], axis=1)

"""encoding"""

df_model = df.copy()

categorical_cols = ['State', 'District', 'Crop', 'Season']

encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    df_model[col] = le.fit_transform(df_model[col].astype(str))
    encoders[col] = le

print("Encoding completed correctly.")
print("Sample States:", encoders['State'].classes_[:5])

"""train / test split"""

X = df_model.drop('Yield', axis=1)
y = df_model['Yield']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training size:", X_train.shape)
print("Testing size:", X_test.shape)

"""train random foret"""

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=20,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("===== Random Forest Results =====")
print("MAE:", mean_absolute_error(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))
print("R2:", r2_score(y_test, y_pred_rf))

"""train xg boost"""

xgb = XGBRegressor(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=6,
    random_state=42,
    objective='reg:squarederror'
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

print("===== XGBoost Results =====")
print("MAE:", mean_absolute_error(y_test, y_pred_xgb))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_xgb)))
print("R2:", r2_score(y_test, y_pred_xgb))

"""save models"""

joblib.dump(rf, '/content/drive/MyDrive/sushnaht_project/final/random_forest_model.pkl', compress=3)
joblib.dump(xgb, '/content/drive/MyDrive/sushnaht_project/final/xgboost_model.pkl', compress=3)
joblib.dump(encoders, '/content/drive/MyDrive/sushnaht_project/final/label_encoders.pkl', compress=3)

print("All models and encoders saved to Google Drive successfully!")

"""test"""

new_data = {
    'State': encoders['State'].classes_[0],
    'District': encoders['District'].classes_[0],
    'Crop': encoders['Crop'].classes_[0],
    'Season': encoders['Season'].classes_[0],
    'Start_Year': 2020
}

new_df = pd.DataFrame([new_data])

for col in categorical_cols:
    new_df[col] = encoders[col].transform(new_df[col])

prediction = rf.predict(new_df)

print("Predicted Yield:", prediction[0])

"""# **Final model comparison plot**"""

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Random Forest Metrics
rf_r2 = r2_score(y_test, y_pred_rf)
rf_mae = mean_absolute_error(y_test, y_pred_rf)
rf_rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))

# XGBoost Metrics
xgb_r2 = r2_score(y_test, y_pred_xgb)
xgb_mae = mean_absolute_error(y_test, y_pred_xgb)
xgb_rmse = np.sqrt(mean_squared_error(y_test, y_pred_xgb))

print("RF R2:", rf_r2)
print("XGB R2:", xgb_r2)

import matplotlib.pyplot as plt

models = ['Random Forest', 'XGBoost']
r2_scores = [rf_r2, xgb_r2]

plt.figure()
plt.bar(models, r2_scores)
plt.title("Model Comparison - R2 Score")
plt.ylabel("R2 Score")
plt.xlabel("Models")
plt.show()

mae_scores = [rf_mae, xgb_mae]

plt.figure()
plt.bar(models, mae_scores)
plt.title("Model Comparison - MAE")
plt.ylabel("MAE")
plt.xlabel("Models")
plt.show()

rmse_scores = [rf_rmse, xgb_rmse]

plt.figure()
plt.bar(models, rmse_scores)
plt.title("Model Comparison - RMSE")
plt.ylabel("RMSE")
plt.xlabel("Models")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Model names
models = ['Random Forest', 'XGBoost']

# Metric values
r2_scores = [rf_r2, xgb_r2]
mae_scores = [rf_mae, xgb_mae]
rmse_scores = [rf_rmse, xgb_rmse]

# X locations
x = np.arange(len(models))
width = 0.25

plt.figure()

# Bars
plt.bar(x - width, r2_scores, width, label='R2')
plt.bar(x, mae_scores, width, label='MAE')
plt.bar(x + width, rmse_scores, width, label='RMSE')

# Labels and Title
plt.xticks(x, models)
plt.ylabel("Score")
plt.title("Model Comparison (Random Forest vs XGBoost)")
plt.legend()

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Model names
models = ['Random Forest', 'XGBoost']

# Metric values
r2_scores = [rf_r2, xgb_r2]
mae_scores = [rf_mae, xgb_mae]
rmse_scores = [rf_rmse, xgb_rmse]

x = np.arange(len(models))
width = 0.25

plt.figure()

bars1 = plt.bar(x - width, r2_scores, width, label='R2')
bars2 = plt.bar(x, mae_scores, width, label='MAE')
bars3 = plt.bar(x + width, rmse_scores, width, label='RMSE')

plt.xticks(x, models)
plt.ylabel("Score")
plt.title("Model Comparison (Random Forest vs XGBoost)")
plt.legend()

# Function to add value labels
def add_labels(bars):
    for bar in bars:
        height = bar.get_height()
        plt.text(
            bar.get_x() + bar.get_width() / 2,
            height,
            f'{height:.3f}',
            ha='center',
            va='bottom'
        )

add_labels(bars1)
add_labels(bars2)
add_labels(bars3)

plt.show()

import matplotlib.pyplot as plt

y_pred = rf.predict(X_test)

plt.figure()
plt.scatter(y_test[:1000], y_pred[:1000])  # plotting 1000 points for clarity
plt.xlabel("Actual Yield")
plt.ylabel("Predicted Yield")
plt.title("Actual vs Predicted Yield (Random Forest)")
plt.show()

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Random Forest Metrics
rf_r2 = r2_score(y_test, y_pred_rf)
rf_mae = mean_absolute_error(y_test, y_pred_rf)
rf_rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))

# XGBoost Metrics
xgb_r2 = r2_score(y_test, y_pred_xgb)
xgb_mae = mean_absolute_error(y_test, y_pred_xgb)
xgb_rmse = np.sqrt(mean_squared_error(y_test, y_pred_xgb))

print("===== FINAL MODEL PERFORMANCE =====\n")

print("Random Forest:")
print(f"R2 Score : {rf_r2:.6f}")
print(f"MAE      : {rf_mae:.6f}")
print(f"RMSE     : {rf_rmse:.6f}\n")

print("XGBoost:")
print(f"R2 Score : {xgb_r2:.6f}")
print(f"MAE      : {xgb_mae:.6f}")
print(f"RMSE     : {xgb_rmse:.6f}")

import pandas as pd
import matplotlib.pyplot as plt

# Create DataFrame
importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
})

# Sort by importance
importance_df = importance_df.sort_values(by='Importance', ascending=True)

plt.figure()
plt.barh(importance_df['Feature'], importance_df['Importance'])
plt.title("Feature Importance - Random Forest")
plt.xlabel("Importance Score")
plt.ylabel("Features")
plt.show()

importance_xgb = pd.DataFrame({
    'Feature': X.columns,
    'Importance': xgb.feature_importances_
})

importance_xgb = importance_xgb.sort_values(by='Importance', ascending=True)

plt.figure()
plt.barh(importance_xgb['Feature'], importance_xgb['Importance'])
plt.title("Feature Importance - XGBoost")
plt.xlabel("Importance Score")
plt.ylabel("Features")
plt.show()